# Generated by Django 6.0 on 2026-01-04 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStaff', models.CharField(choices=[('fr', 'Frontend'), ('ba', 'Backend'), ('ux', 'UX'), ('qa', 'QA'), ('sa', 'Systems Analysis')], max_length=2)),
                ('role', models.CharField(choices=[('ma', 'Manager'), ('wo', 'Worker')], default='wo', max_length=2)),
                ('temp_field', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
