# Generated by Django 6.0 on 2026-01-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='temp_field',
        ),
        migrations.AlterField(
            model_name='person',
            name='nameStaff',
            field=models.CharField(choices=[('fr', 'Frontend'), ('ba', 'Backend'), ('ux', 'UX'), ('qa', 'QA'), ('sa', 'Systems Analysis')], max_length=3),
        ),
        # מחקנו מכאן את CreateModel של Task כי הטבלה כבר קיימת בבסיס הנתונים
    ]