# Generated by Django 5.2.9 on 2026-01-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0002_remove_person_temp_field_alter_person_namestaff_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[("ma", "Manager"), ("wo", "Worker")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nameStaff",
                    models.CharField(
                        choices=[
                            ("fr", "Frontend"),
                            ("ba", "Backend"),
                            ("ux", "UX"),
                            ("qa", "QA"),
                            ("sa", "Systems Analysis"),
                        ],
                        max_length=2,
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True, null=True)),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nw", "New"),
                            ("ip", "In_Process"),
                            ("co", "Completed"),
                        ],
                        default="nw",
                        max_length=2,
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="App1.person",
                    ),
                ),
            ],
        ),
    ]
