# Generated by Django 5.2.9 on 2026-01-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("App1", "0003_alter_person_id_alter_person_role_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(
                choices=[("ma", "Manager"), ("wo", "Worker")],
                default="wo",
                max_length=2,
            ),
        ),
    ]
